on:
  push:
    branches:
      - runner

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      # move to another branch or repository
      - run: docker build . -t c-server
      - run: docker run -v "$(pwd):/app" c-server build
      - uses: actions/upload-artifact@v3
        with:
          name: c-server
          path: ./c-server.bin